<a href="https://colab.research.google.com/github/smeshnayasova61/project/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://spb.hh.ru/applicant/vacancy_response?vacancyId=83244359
Перед вами небольшая таблица (https://clck.ru/34xJwW), содержащая информацию о покупках (cheque) в интернет-магазине в различных регионах (каждая строка - транзакция). Успешная покупка имеет status, равный 1. Необходимо проанализировать данные и ответить на вопрос:

Найдите регион с самым высоким числом успешных покупок за весь заданный период и в ответе укажите число этих покупок.

In [ ]:
import pandas as pd
#import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving test - Sheet1.csv to test - Sheet1.csv

In [ ]:
path = "copied path"
df = pd.read_csv('/content/test - Sheet1.csv')

In [ ]:
df

                      date  status country_name       cheque
0      2022-12-03 00:00:00       1    Казахстан  3,221567698
1      2023-01-02 00:00:00       1     Бразилия  185,6290682
2      2023-02-17 00:00:00       1   Кыргызстан   15,8307312
3      2022-11-04 00:00:00       1       Россия  20,31545493
4      2022-12-11 00:00:00       1   Узбекистан   40,6340304
...                    ...     ...          ...          ...
20131  2022-11-10 00:00:00       1       Россия  22,40901368
20132  2023-02-20 00:00:00       1     Бразилия  171,8991052
20133  2022-12-29 00:00:00       1    Казахстан  3,490416715
20134  2022-12-30 00:00:00       1     Бразилия  168,1639455
20135  2023-02-04 00:00:00       1       Россия  17,25899893

[20136 rows x 4 columns]

In [ ]:
df.dtypes

date            object
status           int64
country_name    object
cheque          object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20136 entries, 0 to 20135
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          20136 non-null  object
 1   status        20136 non-null  int64
 2   country_name  20136 non-null  object
 3   cheque        20136 non-null  object
dtypes: int64(1), object(3)
memory usage: 629.4+ KB

In [ ]:
df['status'].unique ()

array([1, 0])

In [ ]:
df.loc[df['status'] == 1]

                      date  status country_name       cheque
0      2022-12-03 00:00:00       1    Казахстан  3,221567698
1      2023-01-02 00:00:00       1     Бразилия  185,6290682
2      2023-02-17 00:00:00       1   Кыргызстан   15,8307312
3      2022-11-04 00:00:00       1       Россия  20,31545493
4      2022-12-11 00:00:00       1   Узбекистан   40,6340304
...                    ...     ...          ...          ...
20131  2022-11-10 00:00:00       1       Россия  22,40901368
20132  2023-02-20 00:00:00       1     Бразилия  171,8991052
20133  2022-12-29 00:00:00       1    Казахстан  3,490416715
20134  2022-12-30 00:00:00       1     Бразилия  168,1639455
20135  2023-02-04 00:00:00       1       Россия  17,25899893

[19177 rows x 4 columns]

In [ ]:
df['country_name'].unique()

array(['Казахстан', 'Бразилия', 'Кыргызстан', 'Россия', 'Узбекистан',
       'Кот Дивуар', 'Украина', 'Азербайджан', 'Индия', 'Буркина-фасо',
       'Италия', 'Турция', 'Мали', 'Колумбия', 'Болгария', 'Беларусь',
       'Гвинея', 'Польша', 'Германия', 'Швеция', 'Индонезия', 'Кипр',
       'Бельгия', 'Того', 'Чехия', 'Бангладеш', 'Молдова, республика',
       'Израиль', 'Непал', 'Нидерланды', 'Камерун', 'Соединенные штаты',
       'Финляндия', 'Сенегал', 'Соединенное королевство', 'Грузия',
       'Франция', 'Перу', 'Таиланд', 'Португалия', 'Мексика',
       'Таджикистан', 'Нигерия', 'Объединенные арабские эмираты',
       'Корея, республика', 'Китай', 'Аргентина', 'Дания', 'Вьетнам',
       'Япония', 'Афганистан', 'Греция', 'Словакия', 'Бенин', 'Ирландия',
       'Испания', 'Южная африка', 'Словения', 'Саудовская аравия',
       'Гаити', 'Эстония', 'Армения', 'Литва', 'Шри-ланка', 'Люксембург',
       'Марокко', 'Норвегия', 'Чили', 'Пакистан', 'Латвия'], dtype=object)

In [ ]:
df.sort_values(by='country_name', ascending=False)

                      date  status  country_name       cheque
8134   2022-10-01 00:00:00       1        Япония  169,0020838
12143  2023-01-17 00:00:00       1        Япония  17,72129355
10058  2022-10-11 00:00:00       1  Южная африка   757,687417
19421  2022-10-23 00:00:00       1       Эстония  746,8574337
13858  2023-02-04 00:00:00       1       Эстония  925,9455202
...                    ...     ...           ...          ...
15997  2022-12-09 00:00:00       1   Азербайджан  445,6408539
3832   2023-01-02 00:00:00       1   Азербайджан  504,1230194
11508  2022-10-10 00:00:00       1   Азербайджан  683,9490735
13473  2023-02-24 00:00:00       1   Азербайджан  387,3350573
8830   2022-12-21 00:00:00       1   Азербайджан  573,9953192

[20136 rows x 4 columns]

In [ ]:
# Подсчет дубликатов для каждой уникальной строки
df=df.groupby (df.columns.tolist (), as_index= False ). size ()
df

                      date  status country_name        cheque  size
0      2022-10-01 00:00:00       0     Бразилия   158,2899998     1
1      2022-10-01 00:00:00       0        Индия   16,95477403     1
2      2022-10-01 00:00:00       0    Казахстан   3,180654092     1
3      2022-10-01 00:00:00       0    Казахстан   3,247632191     1
4      2022-10-01 00:00:00       0       Россия   20,25535292     2
...                    ...     ...          ...           ...   ...
10900  2023-03-01 00:00:00       1   Узбекистан  0,1912995131     1
10901  2023-03-01 00:00:00       1      Украина   26,27324904     1
10902  2023-03-01 00:00:00       1      Украина   28,20761473     1
10903  2023-03-01 00:00:00       1      Украина   28,66917881     1
10904  2023-03-01 00:00:00       1      Украина    30,6035445     1

[10905 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10905 entries, 0 to 10904
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          10905 non-null  object
 1   status        10905 non-null  int64
 2   country_name  10905 non-null  object
 3   cheque        10905 non-null  object
 4   size          10905 non-null  int64
dtypes: int64(2), object(3)
memory usage: 426.1+ KB

In [ ]:
df=df.sort_values(by='size', ascending=False)
df

                      date  status country_name       cheque  size
9013   2023-02-08 00:00:00       1       Россия  16,84675331    31
8172   2023-01-29 00:00:00       1       Россия  17,35909691    31
9736   2023-02-16 00:00:00       1       Россия  16,33309263    29
7860   2023-01-25 00:00:00       1       Россия   17,6317322    29
9637   2023-02-15 00:00:00       1       Россия  16,45031263    28
...                    ...     ...          ...          ...   ...
4213   2022-12-07 00:00:00       1         Мали  2,148373458     1
4212   2022-12-07 00:00:00       1   Кыргызстан  17,83833252     1
4211   2022-12-07 00:00:00       1   Кот Дивуар  2,647875545     1
4210   2022-12-07 00:00:00       1   Кот Дивуар   2,49966897     1
10904  2023-03-01 00:00:00       1      Украина   30,6035445     1

[10905 rows x 5 columns]

In [ ]:
df=df['size'].max()
df

31

Вывод: Найдите регион с самым высоким числом успешных покупок за весь заданный период и в ответе укажите число этих покупок: Россия, 31 покупка.